# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_openmwcfg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_omwp_cfgwidget(object):
    def setupUi(self, omwp_cfgwidget):
        omwp_cfgwidget.setObjectName("omwp_cfgwidget")
        omwp_cfgwidget.resize(400, 231)
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_cfgwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(omwp_cfgwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.headerWidget = QtWidgets.QWidget(self.widget)
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.headerWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btnEditText = QtWidgets.QPushButton(self.headerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditText.sizePolicy().hasHeightForWidth())
        self.btnEditText.setSizePolicy(sizePolicy)
        self.btnEditText.setObjectName("btnEditText")
        self.horizontalLayout.addWidget(self.btnEditText)
        self.verticalLayout_2.addWidget(self.headerWidget)
        self.configTabs = QtWidgets.QTabWidget(self.widget)
        self.configTabs.setObjectName("configTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.configTabs.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.configTabs)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(omwp_cfgwidget)
        self.configTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(omwp_cfgwidget)

    def retranslateUi(self, omwp_cfgwidget):
        _translate = QtCore.QCoreApplication.translate
        omwp_cfgwidget.setWindowTitle(_translate("omwp_cfgwidget", "Form"))
        self.label_2.setText(_translate("omwp_cfgwidget", "OpenMW.cfg"))
        self.label.setText(_translate("omwp_cfgwidget", "These are the remaining settings in openmw.cfg that aren\'t managed by OpenMW Player. They should be edited here and not in openmw.cfg directly."))
        self.btnEditText.setText(_translate("omwp_cfgwidget", "Edit Raw"))
        self.configTabs.setTabText(self.configTabs.indexOf(self.tab), _translate("omwp_cfgwidget", "Tab 1"))
