# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_groundcover.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_omwp_groundcoverwidget(object):
    def setupUi(self, omwp_groundcoverwidget):
        omwp_groundcoverwidget.setObjectName("omwp_groundcoverwidget")
        omwp_groundcoverwidget.resize(561, 369)
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_groundcoverwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(omwp_groundcoverwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.lstGroundcover = QtWidgets.QListWidget(omwp_groundcoverwidget)
        self.lstGroundcover.setDragEnabled(False)
        self.lstGroundcover.setObjectName("lstGroundcover")
        self.verticalLayout.addWidget(self.lstGroundcover)

        self.retranslateUi(omwp_groundcoverwidget)
        QtCore.QMetaObject.connectSlotsByName(omwp_groundcoverwidget)

    def retranslateUi(self, omwp_groundcoverwidget):
        _translate = QtCore.QCoreApplication.translate
        omwp_groundcoverwidget.setWindowTitle(_translate("omwp_groundcoverwidget", "Form"))
        self.label_2.setText(_translate("omwp_groundcoverwidget", "Groundcover"))
        self.label.setText(_translate("omwp_groundcoverwidget", "Select all plugins that contain grass or other groundcover. These plugins should not be enabled in Mod Organizer."))
