# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_archives.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_omwp_archiveswidget(object):
    def setupUi(self, omwp_archiveswidget):
        omwp_archiveswidget.setObjectName("omwp_archiveswidget")
        omwp_archiveswidget.resize(542, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_archiveswidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(omwp_archiveswidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.lstArchives = QtWidgets.QListWidget(omwp_archiveswidget)
        self.lstArchives.setObjectName("lstArchives")
        self.verticalLayout.addWidget(self.lstArchives)

        self.retranslateUi(omwp_archiveswidget)
        QtCore.QMetaObject.connectSlotsByName(omwp_archiveswidget)

    def retranslateUi(self, omwp_archiveswidget):
        _translate = QtCore.QCoreApplication.translate
        omwp_archiveswidget.setWindowTitle(_translate("omwp_archiveswidget", "Form"))
        self.label_2.setText(_translate("omwp_archiveswidget", "Archives"))
        self.label.setText(_translate("omwp_archiveswidget", "Enable and sort any bsa archives required."))
