# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_texteditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_omwp_texteditor(object):
    def setupUi(self, omwp_texteditor):
        omwp_texteditor.setObjectName("omwp_texteditor")
        omwp_texteditor.resize(700, 500)
        omwp_texteditor.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_texteditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtEditor = QtWidgets.QPlainTextEdit(omwp_texteditor)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.txtEditor.setFont(font)
        self.txtEditor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtEditor.setObjectName("txtEditor")
        self.verticalLayout.addWidget(self.txtEditor)
        self.buttonBox = QtWidgets.QDialogButtonBox(omwp_texteditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(omwp_texteditor)
        QtCore.QMetaObject.connectSlotsByName(omwp_texteditor)

    def retranslateUi(self, omwp_texteditor):
        _translate = QtCore.QCoreApplication.translate
        omwp_texteditor.setWindowTitle(_translate("omwp_texteditor", "Edit Config"))
