# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_settingsrow_comment.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_omwp_settingsrow_comment(object):
    def setupUi(self, omwp_settingsrow_comment):
        omwp_settingsrow_comment.setObjectName("omwp_settingsrow_comment")
        omwp_settingsrow_comment.resize(422, 50)
        omwp_settingsrow_comment.setMinimumSize(QtCore.QSize(0, 40))
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_settingsrow_comment)
        self.verticalLayout.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rowWidget = QtWidgets.QWidget(omwp_settingsrow_comment)
        self.rowWidget.setObjectName("rowWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.rowWidget)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSetting = QtWidgets.QLabel(self.rowWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetting.sizePolicy().hasHeightForWidth())
        self.lblSetting.setSizePolicy(sizePolicy)
        self.lblSetting.setObjectName("lblSetting")
        self.horizontalLayout.addWidget(self.lblSetting)
        self.txtSetting = QtWidgets.QLineEdit(self.rowWidget)
        self.txtSetting.setObjectName("txtSetting")
        self.horizontalLayout.addWidget(self.txtSetting)
        self.verticalLayout.addWidget(self.rowWidget)
        self.lblComment = QtWidgets.QLabel(omwp_settingsrow_comment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblComment.sizePolicy().hasHeightForWidth())
        self.lblComment.setSizePolicy(sizePolicy)
        self.lblComment.setStyleSheet("color: #808080; font-style: italic; padding-left: 9px; padding-right: 9px;")
        self.lblComment.setWordWrap(True)
        self.lblComment.setObjectName("lblComment")
        self.verticalLayout.addWidget(self.lblComment)

        self.retranslateUi(omwp_settingsrow_comment)
        QtCore.QMetaObject.connectSlotsByName(omwp_settingsrow_comment)

    def retranslateUi(self, omwp_settingsrow_comment):
        _translate = QtCore.QCoreApplication.translate
        omwp_settingsrow_comment.setWindowTitle(_translate("omwp_settingsrow_comment", "Form"))
        self.lblSetting.setText(_translate("omwp_settingsrow_comment", "Setting Name"))
        self.lblComment.setText(_translate("omwp_settingsrow_comment", "Comment text goes here"))
