# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_omwp_settingswidget(object):
    def setupUi(self, omwp_settingswidget):
        omwp_settingswidget.setObjectName("omwp_settingswidget")
        omwp_settingswidget.resize(519, 325)
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_settingswidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(omwp_settingswidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.settingsTabs = QtWidgets.QTabWidget(omwp_settingswidget)
        self.settingsTabs.setObjectName("settingsTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 493, 225))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.settingsTabs.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.settingsTabs)

        self.retranslateUi(omwp_settingswidget)
        self.settingsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(omwp_settingswidget)

    def retranslateUi(self, omwp_settingswidget):
        _translate = QtCore.QCoreApplication.translate
        omwp_settingswidget.setWindowTitle(_translate("omwp_settingswidget", "Form"))
        self.label_2.setText(_translate("omwp_settingswidget", "Settings.cfg"))
        self.label.setText(_translate("omwp_settingswidget", "These are the engine settings for OpenMW, they should be edited here and not in the OpenMW Launcher."))
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.tab), _translate("omwp_settingswidget", "Tab 1"))
