# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\curationclub\ui\curationclub_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurationClubMenu(object):
    def setupUi(self, CurationClubMenu):
        CurationClubMenu.setObjectName("CurationClubMenu")
        CurationClubMenu.resize(530, 225)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CurationClubMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentSplitter = QtWidgets.QSplitter(CurationClubMenu)
        self.contentSplitter.setOrientation(QtCore.Qt.Vertical)
        self.contentSplitter.setObjectName("contentSplitter")
        self.tabList = QtWidgets.QTabWidget(self.contentSplitter)
        self.tabList.setObjectName("tabList")
        self.sortTab = QtWidgets.QWidget()
        self.sortTab.setObjectName("sortTab")
        self.tabList.addTab(self.sortTab, "")
        self.updateTab = QtWidgets.QWidget()
        self.updateTab.setObjectName("updateTab")
        self.tabList.addTab(self.updateTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.tabList.addTab(self.helpTab, "")
        self.verticalLayout_2.addWidget(self.contentSplitter)

        self.retranslateUi(CurationClubMenu)
        self.tabList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CurationClubMenu)

    def retranslateUi(self, CurationClubMenu):
        _translate = QtCore.QCoreApplication.translate
        CurationClubMenu.setWindowTitle(_translate("CurationClubMenu", "Form"))
        self.tabList.setTabText(self.tabList.indexOf(self.sortTab), _translate("CurationClubMenu", "Sort"))
        self.tabList.setTabText(self.tabList.indexOf(self.updateTab), _translate("CurationClubMenu", "Update"))
        self.tabList.setTabText(self.tabList.indexOf(self.helpTab), _translate("CurationClubMenu", "Help"))
