# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\plugin\shortcutter\ui\shortcutter_menu.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShortcutterMenu(object):
    def setupUi(self, ShortcutterMenu):
        ShortcutterMenu.setObjectName("ShortcutterMenu")
        ShortcutterMenu.resize(530, 228)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ShortcutterMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentSplitter = QtWidgets.QSplitter(parent=ShortcutterMenu)
        self.contentSplitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.contentSplitter.setObjectName("contentSplitter")
        self.tabList = QtWidgets.QTabWidget(parent=self.contentSplitter)
        self.tabList.setObjectName("tabList")
        self.shortcutTab = QtWidgets.QWidget()
        self.shortcutTab.setObjectName("shortcutTab")
        self.tabList.addTab(self.shortcutTab, "")
        self.updateTab = QtWidgets.QWidget()
        self.updateTab.setObjectName("updateTab")
        self.tabList.addTab(self.updateTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.tabList.addTab(self.helpTab, "")
        self.verticalLayout_2.addWidget(self.contentSplitter)

        self.retranslateUi(ShortcutterMenu)
        self.tabList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ShortcutterMenu)

    def retranslateUi(self, ShortcutterMenu):
        _translate = QtCore.QCoreApplication.translate
        ShortcutterMenu.setWindowTitle(_translate("ShortcutterMenu", "Form"))
        self.tabList.setTabText(self.tabList.indexOf(self.shortcutTab), _translate("ShortcutterMenu", "Shortcut"))
        self.tabList.setTabText(self.tabList.indexOf(self.updateTab), _translate("ShortcutterMenu", "Update"))
        self.tabList.setTabText(self.tabList.indexOf(self.helpTab), _translate("ShortcutterMenu", "Help"))
