# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_groundcover.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_omwp_groundcoverwidget(object):
    def setupUi(self, omwp_groundcoverwidget):
        omwp_groundcoverwidget.setObjectName("omwp_groundcoverwidget")
        omwp_groundcoverwidget.resize(561, 369)
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_groundcoverwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=omwp_groundcoverwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.controlsWidget = QtWidgets.QWidget(parent=omwp_groundcoverwidget)
        self.controlsWidget.setObjectName("controlsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.controlsWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSort = QtWidgets.QLabel(parent=self.controlsWidget)
        self.lblSort.setObjectName("lblSort")
        self.horizontalLayout.addWidget(self.lblSort)
        self.cmbSort = QtWidgets.QComboBox(parent=self.controlsWidget)
        self.cmbSort.setObjectName("cmbSort")
        self.cmbSort.addItem("")
        self.cmbSort.addItem("")
        self.cmbSort.addItem("")
        self.horizontalLayout.addWidget(self.cmbSort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblFilter = QtWidgets.QLabel(parent=self.controlsWidget)
        self.lblFilter.setObjectName("lblFilter")
        self.horizontalLayout.addWidget(self.lblFilter)
        self.txtFilter = QtWidgets.QLineEdit(parent=self.controlsWidget)
        self.txtFilter.setClearButtonEnabled(True)
        self.txtFilter.setObjectName("txtFilter")
        self.horizontalLayout.addWidget(self.txtFilter)
        self.verticalLayout.addWidget(self.controlsWidget)
        self.lstGroundcover = QtWidgets.QListWidget(parent=omwp_groundcoverwidget)
        self.lstGroundcover.setDragEnabled(False)
        self.lstGroundcover.setObjectName("lstGroundcover")
        self.verticalLayout.addWidget(self.lstGroundcover)

        self.retranslateUi(omwp_groundcoverwidget)
        QtCore.QMetaObject.connectSlotsByName(omwp_groundcoverwidget)

    def retranslateUi(self, omwp_groundcoverwidget):
        _translate = QtCore.QCoreApplication.translate
        omwp_groundcoverwidget.setWindowTitle(_translate("omwp_groundcoverwidget", "Form"))
        self.label_2.setText(_translate("omwp_groundcoverwidget", "Groundcover"))
        self.label.setText(_translate("omwp_groundcoverwidget", "Select all plugins that contain grass or other groundcover. These plugins should not be enabled in Mod Organizer."))
        self.lblSort.setText(_translate("omwp_groundcoverwidget", "Sort:"))
        self.cmbSort.setItemText(0, _translate("omwp_groundcoverwidget", "Load Order"))
        self.cmbSort.setItemText(1, _translate("omwp_groundcoverwidget", "A-Z"))
        self.cmbSort.setItemText(2, _translate("omwp_groundcoverwidget", "Z-A"))
        self.lblFilter.setText(_translate("omwp_groundcoverwidget", "Filter:"))
        self.txtFilter.setPlaceholderText(_translate("omwp_groundcoverwidget", "Type to filter..."))
