# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_settingsrowcheck.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_omwp_settingsrow_check(object):
    def setupUi(self, omwp_settingsrow_check):
        omwp_settingsrow_check.setObjectName("omwp_settingsrow_check")
        omwp_settingsrow_check.resize(428, 28)
        omwp_settingsrow_check.setMinimumSize(QtCore.QSize(0, 28))
        self.horizontalLayout = QtWidgets.QHBoxLayout(omwp_settingsrow_check)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSetting = QtWidgets.QLabel(parent=omwp_settingsrow_check)
        self.lblSetting.setObjectName("lblSetting")
        self.horizontalLayout.addWidget(self.lblSetting)
        self.chkSetting = QtWidgets.QCheckBox(parent=omwp_settingsrow_check)
        self.chkSetting.setText("")
        self.chkSetting.setObjectName("chkSetting")
        self.horizontalLayout.addWidget(self.chkSetting)

        self.retranslateUi(omwp_settingsrow_check)
        QtCore.QMetaObject.connectSlotsByName(omwp_settingsrow_check)

    def retranslateUi(self, omwp_settingsrow_check):
        _translate = QtCore.QCoreApplication.translate
        omwp_settingsrow_check.setWindowTitle(_translate("omwp_settingsrow_check", "Form"))
        self.lblSetting.setText(_translate("omwp_settingsrow_check", "Setting Name"))
