# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_settingsrow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_omwp_settingsrow(object):
    def setupUi(self, omwp_settingsrow):
        omwp_settingsrow.setObjectName("omwp_settingsrow")
        omwp_settingsrow.resize(422, 28)
        omwp_settingsrow.setMinimumSize(QtCore.QSize(0, 28))
        self.horizontalLayout = QtWidgets.QHBoxLayout(omwp_settingsrow)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSetting = QtWidgets.QLabel(parent=omwp_settingsrow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetting.sizePolicy().hasHeightForWidth())
        self.lblSetting.setSizePolicy(sizePolicy)
        self.lblSetting.setObjectName("lblSetting")
        self.horizontalLayout.addWidget(self.lblSetting)
        self.txtSetting = QtWidgets.QLineEdit(parent=omwp_settingsrow)
        self.txtSetting.setObjectName("txtSetting")
        self.horizontalLayout.addWidget(self.txtSetting)

        self.retranslateUi(omwp_settingsrow)
        QtCore.QMetaObject.connectSlotsByName(omwp_settingsrow)

    def retranslateUi(self, omwp_settingsrow):
        _translate = QtCore.QCoreApplication.translate
        omwp_settingsrow.setWindowTitle(_translate("omwp_settingsrow", "Form"))
        self.lblSetting.setText(_translate("omwp_settingsrow", "Setting Name"))
