# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\plugin\openmwplayer\ui\openmwplayer_settingsrowcheck_comment.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_omwp_settingsrow_check_comment(object):
    def setupUi(self, omwp_settingsrow_check_comment):
        omwp_settingsrow_check_comment.setObjectName("omwp_settingsrow_check_comment")
        omwp_settingsrow_check_comment.resize(422, 50)
        omwp_settingsrow_check_comment.setMinimumSize(QtCore.QSize(0, 40))
        self.verticalLayout = QtWidgets.QVBoxLayout(omwp_settingsrow_check_comment)
        self.verticalLayout.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rowWidget = QtWidgets.QWidget(parent=omwp_settingsrow_check_comment)
        self.rowWidget.setObjectName("rowWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.rowWidget)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSetting = QtWidgets.QLabel(parent=self.rowWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetting.sizePolicy().hasHeightForWidth())
        self.lblSetting.setSizePolicy(sizePolicy)
        self.lblSetting.setObjectName("lblSetting")
        self.horizontalLayout.addWidget(self.lblSetting)
        self.chkSetting = QtWidgets.QCheckBox(parent=self.rowWidget)
        self.chkSetting.setText("")
        self.chkSetting.setObjectName("chkSetting")
        self.horizontalLayout.addWidget(self.chkSetting)
        self.verticalLayout.addWidget(self.rowWidget)
        self.lblComment = QtWidgets.QLabel(parent=omwp_settingsrow_check_comment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblComment.sizePolicy().hasHeightForWidth())
        self.lblComment.setSizePolicy(sizePolicy)
        self.lblComment.setStyleSheet("color: #808080; font-style: italic; padding-left: 9px; padding-right: 9px;")
        self.lblComment.setWordWrap(True)
        self.lblComment.setObjectName("lblComment")
        self.verticalLayout.addWidget(self.lblComment)

        self.retranslateUi(omwp_settingsrow_check_comment)
        QtCore.QMetaObject.connectSlotsByName(omwp_settingsrow_check_comment)

    def retranslateUi(self, omwp_settingsrow_check_comment):
        _translate = QtCore.QCoreApplication.translate
        omwp_settingsrow_check_comment.setWindowTitle(_translate("omwp_settingsrow_check_comment", "Form"))
        self.lblSetting.setText(_translate("omwp_settingsrow_check_comment", "Setting Name"))
        self.lblComment.setText(_translate("omwp_settingsrow_check_comment", "Comment text goes here"))
