# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\profilesync\ui\profilesync_states.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_groupSyncWidget(object):
    def setupUi(self, groupSyncWidget):
        groupSyncWidget.setObjectName("groupSyncWidget")
        groupSyncWidget.resize(449, 360)
        groupSyncWidget.setMinimumSize(QtCore.QSize(360, 360))
        self.verticalLayout = QtWidgets.QVBoxLayout(groupSyncWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelWidget = QtWidgets.QWidget(groupSyncWidget)
        self.labelWidget.setObjectName("labelWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.labelWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.syncText = QtWidgets.QLabel(self.labelWidget)
        self.syncText.setWordWrap(True)
        self.syncText.setObjectName("syncText")
        self.verticalLayout_2.addWidget(self.syncText)
        self.verticalLayout.addWidget(self.labelWidget)
        self.newStateGroupWidget = QtWidgets.QWidget(groupSyncWidget)
        self.newStateGroupWidget.setObjectName("newStateGroupWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.newStateGroupWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stateGroupLabel = QtWidgets.QLabel(self.newStateGroupWidget)
        self.stateGroupLabel.setObjectName("stateGroupLabel")
        self.horizontalLayout_3.addWidget(self.stateGroupLabel)
        self.createStateGroupText = QtWidgets.QLineEdit(self.newStateGroupWidget)
        self.createStateGroupText.setObjectName("createStateGroupText")
        self.horizontalLayout_3.addWidget(self.createStateGroupText)
        self.createStateGroupBtn = QtWidgets.QPushButton(self.newStateGroupWidget)
        self.createStateGroupBtn.setObjectName("createStateGroupBtn")
        self.horizontalLayout_3.addWidget(self.createStateGroupBtn)
        self.verticalLayout.addWidget(self.newStateGroupWidget)
        self.selectStateGroupWidget = QtWidgets.QWidget(groupSyncWidget)
        self.selectStateGroupWidget.setObjectName("selectStateGroupWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.selectStateGroupWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stateGroupSelect = QtWidgets.QComboBox(self.selectStateGroupWidget)
        self.stateGroupSelect.setObjectName("stateGroupSelect")
        self.horizontalLayout_2.addWidget(self.stateGroupSelect)
        self.deleteStateGroupBtn = QtWidgets.QPushButton(self.selectStateGroupWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteStateGroupBtn.sizePolicy().hasHeightForWidth())
        self.deleteStateGroupBtn.setSizePolicy(sizePolicy)
        self.deleteStateGroupBtn.setObjectName("deleteStateGroupBtn")
        self.horizontalLayout_2.addWidget(self.deleteStateGroupBtn)
        self.verticalLayout.addWidget(self.selectStateGroupWidget)
        self.widget_3 = QtWidgets.QWidget(groupSyncWidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.stateProfileList = QtWidgets.QListWidget(self.splitter)
        self.stateProfileList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.stateProfileList.setObjectName("stateProfileList")
        self.stateCategoryList = QtWidgets.QListWidget(self.splitter)
        self.stateCategoryList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.stateCategoryList.setObjectName("stateCategoryList")
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(groupSyncWidget)
        QtCore.QMetaObject.connectSlotsByName(groupSyncWidget)

    def retranslateUi(self, groupSyncWidget):
        _translate = QtCore.QCoreApplication.translate
        groupSyncWidget.setWindowTitle(_translate("groupSyncWidget", "Form"))
        self.syncText.setText(_translate("groupSyncWidget", "Each profile selected within the group will synchronise the enabled/disabled state of mods within the selected categories. No profile and category combination can be selected more than one time. "))
        self.stateGroupLabel.setText(_translate("groupSyncWidget", "New Group"))
        self.createStateGroupBtn.setText(_translate("groupSyncWidget", "Create"))
        self.deleteStateGroupBtn.setText(_translate("groupSyncWidget", "Delete"))
