# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\profilesync\ui\profilesync_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profileSyncMenuWidget(object):
    def setupUi(self, profileSyncMenuWidget):
        profileSyncMenuWidget.setObjectName("profileSyncMenuWidget")
        profileSyncMenuWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(profileSyncMenuWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(profileSyncMenuWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.groupsTab = QtWidgets.QWidget()
        self.groupsTab.setObjectName("groupsTab")
        self.tabWidget.addTab(self.groupsTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(profileSyncMenuWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(profileSyncMenuWidget)

    def retranslateUi(self, profileSyncMenuWidget):
        _translate = QtCore.QCoreApplication.translate
        profileSyncMenuWidget.setWindowTitle(_translate("profileSyncMenuWidget", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groupsTab), _translate("profileSyncMenuWidget", "Sync Groups"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("profileSyncMenuWidget", "Help"))
