# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\Github\ModOrganizer-Plugins\src\base\ui\progress_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_progressDialog(object):
    def setupUi(self, progressDialog):
        progressDialog.setObjectName("progressDialog")
        progressDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        progressDialog.resize(400, 90)
        progressDialog.setMinimumSize(QtCore.QSize(400, 90))
        progressDialog.setMaximumSize(QtCore.QSize(400, 90))
        self.verticalLayout = QtWidgets.QVBoxLayout(progressDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressWidget = QtWidgets.QWidget(progressDialog)
        self.progressWidget.setObjectName("progressWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.progressWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressTitleText = QtWidgets.QLabel(self.progressWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressTitleText.setFont(font)
        self.progressTitleText.setObjectName("progressTitleText")
        self.verticalLayout_2.addWidget(self.progressTitleText)
        self.progressSubText = QtWidgets.QLabel(self.progressWidget)
        self.progressSubText.setObjectName("progressSubText")
        self.verticalLayout_2.addWidget(self.progressSubText)
        self.verticalLayout.addWidget(self.progressWidget)
        self.progressBar = QtWidgets.QProgressBar(progressDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(progressDialog)
        QtCore.QMetaObject.connectSlotsByName(progressDialog)

    def retranslateUi(self, progressDialog):
        _translate = QtCore.QCoreApplication.translate
        progressDialog.setWindowTitle(_translate("progressDialog", "Dialog"))
        self.progressTitleText.setText(_translate("progressDialog", "TextLabel"))
        self.progressSubText.setText(_translate("progressDialog", "TextLabel"))
