# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\rootbuilder\ui\rootbuilder_exclusions.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_exclusionsTabWidget(object):
    def setupUi(self, exclusionsTabWidget):
        exclusionsTabWidget.setObjectName("exclusionsTabWidget")
        exclusionsTabWidget.resize(373, 280)
        self.verticalLayout = QtWidgets.QVBoxLayout(exclusionsTabWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exclusionsTitle = QtWidgets.QLabel(parent=exclusionsTabWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exclusionsTitle.setFont(font)
        self.exclusionsTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exclusionsTitle.setObjectName("exclusionsTitle")
        self.verticalLayout.addWidget(self.exclusionsTitle)
        self.exclusionsDesc = QtWidgets.QLabel(parent=exclusionsTabWidget)
        self.exclusionsDesc.setWordWrap(True)
        self.exclusionsDesc.setObjectName("exclusionsDesc")
        self.verticalLayout.addWidget(self.exclusionsDesc)
        self.exclusionsTable = QtWidgets.QTableWidget(parent=exclusionsTabWidget)
        self.exclusionsTable.setShowGrid(True)
        self.exclusionsTable.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.exclusionsTable.setCornerButtonEnabled(True)
        self.exclusionsTable.setRowCount(10)
        self.exclusionsTable.setColumnCount(1)
        self.exclusionsTable.setObjectName("exclusionsTable")
        self.exclusionsTable.horizontalHeader().setVisible(False)
        self.exclusionsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.exclusionsTable)

        self.retranslateUi(exclusionsTabWidget)
        QtCore.QMetaObject.connectSlotsByName(exclusionsTabWidget)

    def retranslateUi(self, exclusionsTabWidget):
        _translate = QtCore.QCoreApplication.translate
        exclusionsTabWidget.setWindowTitle(_translate("exclusionsTabWidget", "Form"))
        self.exclusionsTitle.setText(_translate("exclusionsTabWidget", "Exclusions"))
        self.exclusionsDesc.setText(_translate("exclusionsTabWidget", "Files matching the specified fules will be completely ignored by Root Builder. They will not be included in the backup or cache and they will be ignored from any mods they are present in."))
