# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\rootbuilder\ui\rootbuilder_export.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_exportTabWidget(object):
    def setupUi(self, exportTabWidget):
        exportTabWidget.setObjectName("exportTabWidget")
        exportTabWidget.resize(377, 110)
        exportTabWidget.setMinimumSize(QtCore.QSize(0, 110))
        self.verticalLayout = QtWidgets.QVBoxLayout(exportTabWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exportWidget = QtWidgets.QWidget(parent=exportTabWidget)
        self.exportWidget.setObjectName("exportWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.exportWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importButton = QtWidgets.QPushButton(parent=self.exportWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout.addWidget(self.importButton)
        self.exportButton = QtWidgets.QPushButton(parent=self.exportWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.label = QtWidgets.QLabel(parent=self.exportWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.exportWidget)
        self.resetWidget = QtWidgets.QWidget(parent=exportTabWidget)
        self.resetWidget.setObjectName("resetWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.resetWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resetButton = QtWidgets.QPushButton(parent=self.resetWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.label_2 = QtWidgets.QLabel(parent=self.resetWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.resetWidget)

        self.retranslateUi(exportTabWidget)
        QtCore.QMetaObject.connectSlotsByName(exportTabWidget)

    def retranslateUi(self, exportTabWidget):
        _translate = QtCore.QCoreApplication.translate
        exportTabWidget.setWindowTitle(_translate("exportTabWidget", "Form"))
        self.importButton.setText(_translate("exportTabWidget", "Import"))
        self.exportButton.setText(_translate("exportTabWidget", "Export"))
        self.label.setText(_translate("exportTabWidget", "You can import and export Root Builder configuration files here. This can be used to backup your current settings or to share them with other people."))
        self.resetButton.setText(_translate("exportTabWidget", "Reset"))
        self.label_2.setText(_translate("exportTabWidget", "This button will reset Root Builder\'s configuration to the default settings."))
