# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\rootbuilder\ui\rootbuilder_install.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_installDialogMenu(object):
    def setupUi(self, installDialogMenu):
        installDialogMenu.setObjectName("installDialogMenu")
        installDialogMenu.resize(375, 71)
        installDialogMenu.setMinimumSize(QtCore.QSize(375, 0))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(installDialogMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modNameLabel = QtWidgets.QLabel(parent=installDialogMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.modNameLabel.setFont(font)
        self.modNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.modNameLabel.setObjectName("modNameLabel")
        self.verticalLayout_2.addWidget(self.modNameLabel)
        self.modNameCombo = QtWidgets.QComboBox(parent=installDialogMenu)
        self.modNameCombo.setEditable(True)
        self.modNameCombo.setObjectName("modNameCombo")
        self.verticalLayout_2.addWidget(self.modNameCombo)
        self.widget = QtWidgets.QWidget(parent=installDialogMenu)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.manualBtn = QtWidgets.QPushButton(parent=self.widget)
        self.manualBtn.setObjectName("manualBtn")
        self.horizontalLayout.addWidget(self.manualBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.installBtn = QtWidgets.QPushButton(parent=self.widget)
        self.installBtn.setDefault(True)
        self.installBtn.setObjectName("installBtn")
        self.horizontalLayout.addWidget(self.installBtn)
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(installDialogMenu)
        QtCore.QMetaObject.connectSlotsByName(installDialogMenu)

    def retranslateUi(self, installDialogMenu):
        _translate = QtCore.QCoreApplication.translate
        installDialogMenu.setWindowTitle(_translate("installDialogMenu", "Form"))
        self.modNameLabel.setText(_translate("installDialogMenu", "Mod Name"))
        self.manualBtn.setText(_translate("installDialogMenu", "Manual"))
        self.installBtn.setText(_translate("installDialogMenu", "Install"))
        self.cancelBtn.setText(_translate("installDialogMenu", "Cancel"))
