# Form implementation generated from reading ui file 'D:\Repos\ModOrganizer-Plugins\src\plugin\pluginfinder\ui\pluginfinder_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pluginFinderMenuWidget(object):
    def setupUi(self, pluginFinderMenuWidget):
        pluginFinderMenuWidget.setObjectName("pluginFinderMenuWidget")
        pluginFinderMenuWidget.resize(427, 683)
        self.verticalLayout = QtWidgets.QVBoxLayout(pluginFinderMenuWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=pluginFinderMenuWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.finderTab = QtWidgets.QWidget()
        self.finderTab.setObjectName("finderTab")
        self.tabWidget.addTab(self.finderTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(pluginFinderMenuWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pluginFinderMenuWidget)

    def retranslateUi(self, pluginFinderMenuWidget):
        _translate = QtCore.QCoreApplication.translate
        pluginFinderMenuWidget.setWindowTitle(_translate("pluginFinderMenuWidget", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.finderTab), _translate("pluginFinderMenuWidget", "Finder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("pluginFinderMenuWidget", "Help"))
